config/routes.rb
Skitchen::Application.routes.draw do

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in" 

  get "sign_up" => "users#new", :as =>"sign_up"

  resources :ios_devices
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :groups, :except => [:update, :edit]
  resources :groupnotifications, :except => [:update, :edit] do
    member do
      get :dispatch_gn
    end
  end

  root :to => "pages#home"
    
  

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password, :password_confirmation
  
  attr_accessor :password
  before_save :encrypt_password
  
  
  validates(:name, :presence => true,
	          :uniqueness => { :case_sensitive => false })
  
  validates( :password, :presence => true,
	   	       :confirmation => true,
             :length => { :within => 6..20 }) 

  

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
  
  class << self
    def authenticate(name, submitted_password)
      user = find_by_name(name)
      if user && user.password_hash == BCrypt::Engine.hash_secret(submitted_password, user.password_salt)
        user
      else
        nil
      end
    end

    def authenticate_with_salt(id, cookie_salt)
      user = find_by_id(id)
      (user && user.salt == cookie_salt) ? user : nil
    end
  end
  
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :signed_in? 
  
  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to users_path, flash[:notice] => "New user created!"
    else
      render "new"
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "User info updated."
      redirect_to @user
    else
      @title = "Edit user"
      render 'edit'
    end
  end
  
 
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_path
  end
   

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<tr>
  <td><%= link_to user.id, user_path(user) %></td>
  <td><%= link_to user.name, user_path(user) %></td>
  <td align="center"><%= link_to "(X_X)", user, :method => :delete, :confirm => "Delete this user?", :title => "Delete #{user.name}" %></td>
</tr>

app/views/users/edit.html.erb
<h2>Edit User</h2>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h3>Form is invalid</h3>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>

app/views/users/index.html.erb
<h2>Admin Index</h2>

<p>Below is a table displaying all administrators. The names link to the individual admin profile pages. Click here to create a <%= link_to "new admin.", new_user_path %></p>  

<center>
<table>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Delete</th>
  </tr>
  <% @users.each do |user| %>
    <%= render :partial => "user", :locals => {:user => user} %>
  <% end %>
</table>
</center> 

app/views/users/new.html.erb
<h2>Create New User</h2>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h3>Form is invalid</h3>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>

app/views/users/show.html.erb
<h2><%= @user.name %> User-Info</h2>