config/routes.rb
Skitchen::Application.routes.draw do

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in" 

  get "sign_up" => "users#new", :as =>"sign_up"

  resources :ios_devices
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :groups, :except => [:update, :edit]
  resources :groupnotifications, :except => [:update, :edit] do
    member do
      get :dispatch_gn
    end
  end

  root :to => "pages#home"
    
  

end

app/models/groupnotification.rb
class Groupnotification < ActiveRecord::Base
  after_create :create_notifications #needs to be after for a self.id to be established
  #after_update :update_notifications #needs to be after for a self.id to be established
  before_destroy :destroy_notifications

  
  default_scope :order => 'groupnotifications.created_at DESC'
  has_many :notifications, :class_name => 'APN::Notification'
  belongs_to :group
  

  attr_accessible :sound, :alert, :badge, :sent_at, :group_id
  
  validates(:alert, :presence => true, :length => { :maximum => 140 }) 
  validates(:badge, :presence => true, :numericality => true)
  validates(:group_id, :presence => true, :numericality => true)
  
  private
  
  #create individual notifications for each device in the group specified in the group notification
  def create_notifications 
    @devices = Group.find_by_id(self.group_id).devices
    @devices.each do |device|
      device.notifications.create(:groupnotification_id => self.id, :sound => self.sound, :alert => self.alert, :badge => self.badge)
    end
  end
  
  #edit individual notifications for each device in the group specified in the group notification
#  def update_notifications
#    @notifications = self.notifications
#    @notifications.each do |n|
#      n.update_attributes(:groupnotification_id => self.id, :sound => self.sound, :alert => self.alert, :badge => self.badge)
#    end
#  end
  
  #delete individual notifications for each device in the group specified in the group notification
  def destroy_notifications
    @notifications = self.notifications
    @notifications.each do |n|
      n.delete
    end   
  end
  

end

app/controllers/groupnotifications_controller.rb
class GroupnotificationsController < ApplicationController

  before_filter :signed_in?
  before_filter :timestamp_check, :only => [:index]
   
  
  def index
    @groupnotifications = Groupnotification.all
  end
  
  def new
    @groupnotification = Groupnotification.new
  end
  
  def edit
    @groupnotification = Groupnotification.find(params[:id])
  end
  
  def show
    @groupnotification = Groupnotification.find(params[:id])
  end
  
  def create
    @groupnotification = Groupnotification.new(params[:groupnotification])
    if @groupnotification.save
      redirect_to groupnotifications_path, flash[:notice] => "New group notification created!"
    else
      render "new"
    end
  end
  
  def update
    @groupnotification = Groupnotification.find(params[:id])
    if @groupnotification.update_attributes(params[:groupnotification])
      flash[:success] = "Group notification updated."
      redirect_to @groupnotification
    else
      @title = "Edit group notification"
      render 'edit'
    end
  end
  
 
  def destroy
    Groupnotification.find(params[:id]).destroy
    flash[:success] = "Group notification destroyed."
    redirect_to groupnotifications_path
  end
   
  def dispatch_gn
    flash[:notice] = "Send function invoked, sending notifications..."
    notes = Groupnotification.find(params[:id]).notifications
    APN::Notification.send_notifications(notes)
    redirect_to groupnotifications_path
  end

  def timestamp_check
    if Groupnotification.where(:sent_at=>nil).any?
      Groupnotification.where(:sent_at=>nil).each do |gn|
        if gn.notifications.where(:sent_at=>nil).empty?
          gn.update_attribute(:sent_at, gn.notifications.last.sent_at)
          gn.notifications.each do |n|
            n.delete
          end
        end
      end
    end
  end
  
end

app/helpers/groupnotifications_helper.rb
module GroupnotificationsHelper
end

app/views/groupnotifications/_gn.html.erb
<tr>
  <td><%= link_to gn.id, groupnotification_path(gn) %></td>
  <td><%= Group.find(gn.group_id).name %></td>
  <td><%= gn.alert %></td>
  <% if gn.sent_at %>
    <td><%= gn.sent_at.localtime %></td>
  <% else %>
    <td>not yet sent</td>
   <% end %>
</tr>

app/views/groupnotifications/create.html.erb
<h1>Groupnotifications#create</h1>
<p>Find me in app/views/groupnotifications/create.html.erb</p>

app/views/groupnotifications/edit.html.erb
<h2>Edit Group Notification</h2>


<%= form_for @groupnotification do |f| %>
  <% if @groupnotification.errors.any? %>
    <div class="error_messages">
      <h3>Form is invalid</h3>
      <ul>
        <% for message in @groupnotification.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label "Target Group" %><br />
    <%= collection_select :groupnotification, :group_id, Group.all, :id, :name, {}, {} %></br>
  </p>
  <p>
    <%= f.label :alert %><br />
    <%= f.text_field :alert, :size => "80" %>
  </p>
  <p>
    <%= f.label :badge %><br />
    <%= f.text_field :badge %>
  </p>


  <p class="button"><%= f.submit "Update Group Notification", :class => "button"%></p>
<% end %>

app/views/groupnotifications/index.html.erb
<h2>Group Notification Index</h2>

<p>Below is a table displaying all group notifications. Click here to create a <%= link_to "new group notification.", new_groupnotification_path %></p>  

<center>
<table>
  <tr>
    <th>ID</th>
    <th>Recipient Group</th>
    <th>Message</th>
    <th>Sent At</th>
  </tr>
  <% @groupnotifications.each do |gn| %>
    <%= render :partial => "gn", :locals => {:gn => gn} %>
  <% end %>
</table>
</center> 

app/views/groupnotifications/new.html.erb
<h2>Create New Group Notification</h2>


<%= form_for @groupnotification do |f| %>
  <% if @groupnotification.errors.any? %>
    <div class="error_messages">
      <h3>Form is invalid</h3>
      <ul>
        <% for message in @groupnotification.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label "Target Group" %><br />
    <%= collection_select :groupnotification, :group_id, Group.all, :id, :name, {}, {} %></br>
  </p>
  <p>
    <%= f.label :alert %><br />
    <%= f.text_field :alert, :size => "80" %>
  </p>
  <p>
    <%= f.label :badge %><br />
    <%= f.text_field :badge %>
  </p>


  <p class="button"><%= f.submit "Create Group Notification", :class => "button"%></p>
<% end %>

app/views/groupnotifications/show.html.erb
<h2>Info for Group Notification #<%= @groupnotification.id %></h2>
<p>Click here to <%= link_to "delete this group notification.", @groupnotification, :method => :delete, :confirm => "Delete this group notification?", :title => "Delete #{@groupnotification.id}" %></p>
<% if @groupnotification.sent_at.nil? %>
<p>Click here to <%= link_to "send this group notification.", dispatch_gn_groupnotification_path %></p>
<% end %>
<h3>Recipient Group:</h3>
<p><%= Group.find(@groupnotification.group_id).name %></p>
<h3>Sent At:</h3>
  <% if @groupnotification.sent_at %>
    <p><%= @groupnotification.sent_at.localtime %></p> 
  <% else %>  
    <p>not yet sent</p> 
  <% end %>
<h3>Badge:</h3>
<p><%= @groupnotification.badge %></p>
<h3>Alert:</h3>
<p><%= @groupnotification.alert %></p>