config/routes.rb
Skitchen::Application.routes.draw do

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in" 

  get "sign_up" => "users#new", :as =>"sign_up"

  resources :ios_devices
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :groups, :except => [:update, :edit]
  resources :groupnotifications, :except => [:update, :edit] do
    member do
      get :dispatch_gn
    end
  end

  root :to => "pages#home"
    
  

end

app/views/layouts/_header.html.erb
<!--header -->
	<div id="header">			
		<h1 id="logo-text"><%= link_to "Stuart's Kitchen", root_path %></h1>		
		<p id="intro">
		An admin page for Stuart's Kitchen (powered by Appetites), where CRUD functions can be invoked for Users, Groups, and Notifications. 
		</p>		
<!--		
		<div id="nav">
			<ul>
				<li id="current"><a href="index.html">Home</a></li>
				<li><a href="index.html">Link-2</a></li>
				<li><a href="index.html">Link-3</a></li>
				<li><a href="index.html">Link-4</a></li>		
			</ul>		
		</div>	
-->					
	</div>

app/views/layouts/_sidebar.html.erb
<!-- sidebar starts -->
<div id="sidebar">
      <% if current_user %>
        <h3>Logged in as <%= current_user.name %></h3>
        <p>Click here to <%= link_to "log out.", log_out_path %></p>
      <% else %>
        <h3>Sign In</h3>
        <p>Click here to <%= link_to "log in.", log_in_path %></p>
      <% end %>

	<h3>Sidebar Menu</h3>
	<ul class="sidemenu">				
		<li><%= link_to "Home", root_path %></li>
		<li><%= link_to "Users", users_path %></li>
		<li><%= link_to "Group Notifications", groupnotifications_path %></li>
	</ul>	
		
			
			
				
<!-- sidebar ends -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stuart's Kitchen</title>
  <%= stylesheet_link_tag "Colourise" %> 
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<!-- wrap starts here -->
<div id="wrap">

<%= render 'layouts/header' %>
	
	  <% flash.each do |key, value| %>
    	    <div class="flash_<%= key %>"><%= value %> </div>
	  <% end %>
	
	
<div id="content-wrap">
				
		<div id="main">

      <%= yield %>
      				
				
			<br />	

		<!-- main ends -->	
		</div>
		
		<%= render 'layouts/sidebar' %>

		
<!-- content-wrap ends-->	
</div>


</body>
</html>